### ISSUE TITLE
Speedo Analyze Command Issues

### ISSUE THREAD

**Issue by Borets** [saucelabs/speedo#23]
As I started to play around with the analyze command and discovered the following problems

**1) Speedo analyze consistently returning failure**

Example provided below

![image](https://user-images.githubusercontent.com/3301693/56056309-a3c57f00-5d10-11e9-8086-772cd597f3d1.png)

**2. It’s unclear why the error occurred.**

- We should provide users with information as to why the test failed(e.g. a number is outside of the expected baselines and list out what the expected baselines should be)

- We are not highlighting the URL where the issue occurred

**3. Even though the failures are displayed after speedo analyze the step in CI doesn’t actually fail**

- not sure if something else needs to be outputted

**4. Since Fernando has mentioned that there is no easy way to confirm the regression on the first run we should consider either allowing to accept regressions on the first run or allowing to run speedo analyze in a way that it checks for change points rather than failing the first time a number is outside of predicted baselines.**

**5. In Jenkins logs, you can’t really see the shadows and we should be very clear as to which metrics are being validated.**

![image](https://user-images.githubusercontent.com/3301693/56056323-ab852380-5d10-11e9-909c-7945a55bf96b.png)

if you think we should display other metrics we should be very clear with what is being checked by speedo vs what other data is displayed just for the informational purposes

**Comment by yfangsl** [comment]
I'm splitting off #1 into its own issue and have a fix for it

**Comment by yfangsl** [comment]
5) Has been split off into https://github.com/saucelabs/speedo/issues/30

4) I think is its own thing and should be discussed further for a different story

**Comment by yfangsl** [comment]
I think the relevant issues have been closed.  If 4. is a thing it should be a jira story I think.
