### ISSUE TITLE
--throttleCpu command is not properly passing parameters to the test

### ISSUE THREAD

**Issue by Borets** [saucelabs/speedo#45]
It looks like whenever I use speedo's `--throttleCpu 0' the CPU throttle doesn't actually remove the CPU throttle and it is still set to 4 

**Steps to Reproduce**

Use speedo run with the following command
--> `speedo run https://www.amazon.com --throttleNetwork online --throttleCpu 0` 

**Screenshot**
![image](https://user-images.githubusercontent.com/3301693/56666202-0e5fae80-6671-11e9-95d6-032c45a1380e.png)

**Comment by yfangsl** [comment]
This is actually an interesting edge case.  setting it to 0 basically disables it, but the code then sees that it wasn't set so sets it back to 4 by default.  I guess currently to run unthrottled users should use "1" instead of "0"

**Comment by christian-bromann** [comment]
Fixed in #53
