### ISSUE TITLE
Pass the throttling parameters into the job name 

### ISSUE THREAD

**Issue by Borets** [saucelabs/speedo#46]
With the introduction of CPU & Network throttling, we want to make sure that users are able to run tests with various CPU and network combinations as part of the same build. Unfortunately, currently, independently of the settings with which speedo runs the job name remains the same thus making it impossible to find performance regressions for each of the test cases separately since each setting has a direct impact on the metrics. 

AC:
* Pass the network and CPU throttling parameters directly into the test name so that users are able to run tests across multiple throttling parameters as part of the same build.

**Comment by christian-bromann** [comment]
Fixed in #52
