### ISSUE TITLE
Invalid performance measurements assertion

### ISSUE THREAD

**Issue by adambabik** [saucelabs/speedo#51]
I run a test and got the following results:
```
Performance Results
===================
load: 1.3s
timeToFirstByte: 442ms
firstPaint: 858ms
firstContentfulPaint: 858ms
firstMeaningfulPaint: 858ms
domContentLoaded: 540ms
timeToFirstInteractive: 858ms
speedIndex: 891ms
perceptualSpeedIndex: 895ms
pageWeight: 77.8 kB
pageWeightEncoded: 0 B

Performance assertions failed! ❌
Expected load to be between 1.3s and 1.3s but was actually 1.3s
```

It looks like there is a bug with comparing approximate numbers.

**Comment by christian-bromann** [comment]
> It looks like there is a bug with comparing approximate numbers.

This comes from the API, more precisely when we call the WebDriver extension (`/session/:sessionId/sauce/ondemand/performance`). This can't be fixed in Speedo.
