### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/speedo#85]
With GitHub Actions being better integrated into GitHub it makes sense to get rid of TravisCI and run all our tests here.

**Comment by abskmj** [comment]
@christian-bromann I can pick this up. I have written GitHub actions based workflows for a few of my npm packages.

**Comment by christian-bromann** [comment]
Awesome, let me know if you need anything.

**Comment by abskmj** [comment]
Thanks!

Currently, `./bin/speedo run http://www.saucedemo.com -n "Speedo CI Build"` step is failing with the below error. I can set up the workflow to take them from the Github secrets. How do I get the values for testing purposes?

```
Your Sauce credentials are missing!
Either set 'SAUCE_USERNAME' and 'SAUCE_ACCESS_KEY' in your environment or
provide them as parameter
```

**Comment by christian-bromann** [comment]
@abskmj this is something I can setup, can you test with a temporary account to see if the pipeline runs through and then just submit a PR?

**Comment by abskmj** [comment]
I was able to create a temporary account and check the pipeline. Now, it is going through. Thanks.

I have a question about the deploy step. When exactly does it run, does it only when you create a tag?

```
deploy:
  provider: script
  script: "npm install && npm run docker"
  on:
    tags: true
```

**Comment by christian-bromann** [comment]
> does it only when you create a tag?

Yes.

**Comment by abskmj** [comment]
I have raised a pull request #87 with related changes. I have added 2 workflows, 
- one to run test cases when new code is pushed on any branch or a pull request is created on any branch.
- other to build and push docker images when a new tag is pushed.

**Comment by christian-bromann** [comment]
Awesome, let's continue our conversations there.
